In [40]:
import pandas as pd

In [41]:
ppg_finalised_features=pd.read_csv('PPG_Finalised.csv')#Reading the ppg finalised dataset

In [42]:
ppg_finalised_features.head()

Sex(M/F)  Age(year)  Height(cm)  ...        20        21        22
0         0         45         152  ... -1.354707 -3.518339 -0.817157
1         0         50         157  ... -0.099423 -0.302771  1.489630
2         0         47         150  ... -0.083866  0.131694 -1.392140
3         1         45         172  ... -0.171474 -0.923647  0.402769
4         0         46         155  ... -0.004746 -0.217980  1.494885

[5 rows x 30 columns]

In [43]:
len(ppg_finalised_features)

628

In [44]:
X=ppg_finalised_features.drop("Hypertension",axis=1)#independent features

In [45]:
X.head()

Sex(M/F)  Age(year)  Height(cm)  ...        20        21        22
0         0         45         152  ... -1.354707 -3.518339 -0.817157
1         0         50         157  ... -0.099423 -0.302771  1.489630
2         0         47         150  ... -0.083866  0.131694 -1.392140
3         1         45         172  ... -0.171474 -0.923647  0.402769
4         0         46         155  ... -0.004746 -0.217980  1.494885

[5 rows x 29 columns]

In [46]:
Y=ppg_finalised_features['Hypertension']#dependent features

In [47]:
Y.head()

0    Stage 2 hypertension
1    Stage 2 hypertension
2                  Normal
3         Prehypertension
4         Prehypertension
Name: Hypertension, dtype: object

In [48]:
params={
 "learning_rate"    : [0.001,0.01,0.02,0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [49]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import xgboost
X.shape

(628, 29)

In [50]:
classifier=xgboost.XGBClassifier()

In [51]:
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='recall_weighted',n_jobs=-1,cv=10,verbose=3)

In [52]:
random_search.fit(X,Y)

Fitting 10 folds for each of 5 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:    7.7s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   15.1s finished


RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0,
                                           reg_lambda=1, s...
                   iid='deprecated', n_iter=5, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.3, 0.4, 0.5,
                                           

In [53]:
xgboost_best_estimator=random_search.best_estimator_

In [54]:
random_search.best_params_

{'colsample_bytree': 0.5,
 'gamma': 0.4,
 'learning_rate': 0.1,
 'max_depth': 8,
 'min_child_weight': 7}

In [39]:
classifier=xgboost.xgboost_best_estimator



In [55]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
score=cross_val_score(classifier,X,Y,cv=cv)

In [56]:
score

array([0.6984127 , 0.76190476, 0.85714286, 0.77777778, 0.87301587,
       0.77777778, 0.80952381, 0.85714286, 0.79032258, 0.74193548,
       0.76190476, 0.82539683, 0.82539683, 0.71428571, 0.82539683,
       0.77777778, 0.77777778, 0.6984127 , 0.82258065, 0.79032258,
       0.73015873, 0.79365079, 0.80952381, 0.74603175, 0.76190476,
       0.73015873, 0.85714286, 0.88888889, 0.82258065, 0.72580645])

In [57]:
score.mean()

0.7876685441201572

In [58]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2

In [59]:
parameters = {
    "n_estimators":[5,50,100,150,200,250,500],
    "max_depth":[i for i in range(50)],
    "learning_rate":[0.15,0.1,0.05,0.01,0.005,0.001],
      'max_depth':[i for i in range(20)],  'max_leaf_nodes':[i for i in range(50)]

}

In [60]:
clf = GradientBoostingClassifier()

In [61]:
random_search=RandomizedSearchCV(clf,param_distributions=parameters,n_iter=5,scoring='recall_weighted',n_jobs=-1,cv=10,verbose=3)

In [24]:
random_search.fit(X,Y)

Fitting 10 folds for each of 5 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  3.9min finished


RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                                        criterion='friedman_mse',
                                                        init=None,
                                                        learning_rate=0.1,
                                                        loss='deviance',
                                                        max_depth=3,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                   

In [25]:
gradientboost_best_estimator=random_search.best_estimator_

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=9,
                           max_features=None, max_leaf_nodes=20,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [26]:
clf = gradientboost_best_estimator


In [27]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
score=cross_val_score(clf,X,Y,cv=cv)

In [28]:
score

array([0.76190476, 0.79365079, 0.87301587, 0.88888889, 0.92063492,
       0.84126984, 0.82539683, 0.88888889, 0.80645161, 0.83870968,
       0.84126984, 0.85714286, 0.85714286, 0.77777778, 0.88888889,
       0.88888889, 0.84126984, 0.84126984, 0.88709677, 0.79032258,
       0.76190476, 0.88888889, 0.93650794, 0.88888889, 0.82539683,
       0.80952381, 0.88888889, 0.92063492, 0.79032258, 0.77419355])

In [29]:
score.mean()

0.8465011094043351

In [30]:
import numpy as np
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}

In [31]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [32]:
random_search=RandomizedSearchCV(rf,param_distributions=random_grid,n_iter=5,scoring='recall_weighted',n_jobs=-1,cv=10,verbose=3)

In [33]:
random_search.fit(X,Y)

Fitting 10 folds for each of 5 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  2.0min finished


RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
              

In [34]:
randomforest_best_estimator=random_search.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=557, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=800,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
rf=randomforest_best_estimator

In [36]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
score=cross_val_score(rf,X,Y,cv=cv)

In [37]:
score

array([0.73015873, 0.74603175, 0.9047619 , 0.84126984, 0.9047619 ,
       0.84126984, 0.76190476, 0.87301587, 0.80645161, 0.85483871,
       0.84126984, 0.79365079, 0.85714286, 0.76190476, 0.88888889,
       0.82539683, 0.80952381, 0.77777778, 0.82258065, 0.77419355,
       0.76190476, 0.85714286, 0.87301587, 0.80952381, 0.84126984,
       0.77777778, 0.79365079, 0.85714286, 0.82258065, 0.72580645])

In [38]:
score.mean()

0.8178870114353988